name: Staging Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/govuk-digital-backbone/govuk-notify-smtp-relay:latest
          docker push ghcr.io/govuk-digital-backbone/govuk-notify-smtp-relay:latest
