name: GHCR Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and Push Image'
        run: |
          # Force everything to lowercase
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/$OWNER/gcnotify-smtp-relay
          VERSION=latest
          echo "Building $IMAGE_ID:$VERSION"
          docker build . --tag $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION